import random
from datetime import datetime, timezone


def generate_test_dna_file(output_path, num_entries=500000):
    chromosomes = [str(i) for i in range(1, 23)] + ['X', 'Y', 'MT']
    bases = ['A', 'T', 'C', 'G']

    header = [
        "#AncestryDNA raw data download",
        f"#This file was generated by AncestryDNA at: {datetime.now(timezone.utc).strftime('%d/%m/%Y %H:%M:%S')} UTC",
        "#Data was collected using AncestryDNA array version: V2.0",
        "#Data is formatted using AncestryDNA converter version: V1.0",
        "#Below is a text version of your DNA file from Ancestry.com DNA, LLC.  THIS",
        "#INFORMATION IS FOR YOUR PERSONAL USE AND IS INTENDED FOR GENEALOGICAL RESEARCH",
        "#ONLY.  IT IS NOT INTENDED FOR MEDICAL, DIAGNOSTIC, OR HEALTH PURPOSES.  THE EXPORTED DATA IS",
        "#SUBJECT TO THE ANCESTRY TERMS AND CONDITIONS, BUT PLEASE BE AWARE THAT THE",
        "#DOWNLOADED DATA WILL NO LONGER BE PROTECTED BY OUR SECURITY MEASURES.",
        "#WHEN YOU DOWNLOAD YOUR RAW DNA DATA, YOU ASSUME ALL RISK OF STORING,",
        "#SECURING AND PROTECTING YOUR DATA.  FOR MORE INFORMATION, SEE ANCESTRYDNA FAQS.",
        "#",
        "#Genetic data is provided below as five TAB delimited columns.  Each line",
        "#corresponds to a SNP.  Column one provides the SNP identifier (rsID where",
        "#possible).  Columns two and three contain the chromosome and basepair position",
        "#of the SNP using human reference build 37.1 coordinates.  Columns four and five",
        "#contain the two alleles observed at this SNP (genotype).  The genotype is reported",
        "#on the forward (+) strand with respect to the human reference.",
        "rsid\tchromosome\tposition\tallele1\tallele2"
    ]

    with open(output_path, 'w') as f:
        # Write header
        f.write('\n'.join(header) + '\n')

        # Generate entries
        used_positions = set()
        for _ in range(num_entries):
            chromosome = random.choice(chromosomes)
            position = random.randint(1, 249250621)  # Max length of chromosome 1

            # Ensure unique position per chromosome
            while (chromosome, position) in used_positions:
                position = random.randint(1, 249250621)
            used_positions.add((chromosome, position))

            rsid = f"rs{random.randint(1, 999999999)}"
            allele1 = random.choice(bases)
            allele2 = random.choice(bases)

            line = f"{rsid}\t{chromosome}\t{position}\t{allele1}\t{allele2}\n"
            f.write(line)


if __name__ == "__main__":
    output_file = "large_test_ancestry_data.txt"
    generate_test_dna_file(output_file)
    print(f"Generated test DNA file with 500,000 entries at {output_file}")
